# This is a basic workflow to help you get started with Actions

name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Start server
      run: |
        nohup npm start &

    - name: Wait for server to start
      run: |
        sleep 5

    - name: Test Hello World
      run: |
        OUTPUT=$(curl -f http://127.0.0.1:3000/)
        if [[ "$OUTPUT" != "Hello World" ]]; then
          echo "Test failed: Expected 'Hello World' but got '$OUTPUT'"
          exit 1
        else
          echo "Test passed: Received 'Hello World'"
        fi

    - name: Run test Script
      run: |
        bash run_tests.sh

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/0x13v.com/2sd256.0x13v.com/src
          git pull origin main
        # npm install
        # pm2 restart my-app